### ISSUE TITLE
new line problem ..

### ISSUE THREAD

**Issue by mohammadrezamajd** [michaelosthege/TCD.Controls.Keyboard#1]
hi .. when i click on new line button the  Exception "System.ArgumentOutOfRangeException" is occurred  in the following code :
`  
                         box.Text = text.Insert(currentSelectionStart, (string)arg);
`

**Comment by michaelosthege** [comment]
hi - thanks for reporting!
I can have a look at it this evening.
In the meantime, you could clone or download this repository (https://github.com/michaelosthege/TCD.Controls.Keyboard/archive/master.zip) and try to reproduce/fix it with the sample application. That would make it easier for me to update the repo and also the NuGet package.

**Comment by michaelosthege** [comment]
@mohammadrezamajd I can't reproduce it. What are the exact steps that you took? (letters typed, text selected..)
